### ISSUE TITLE
ImportError raised from the MovedModule.__getattr__ method

### ISSUE THREAD

**Issue by SylvainDe** [benjaminp/six#174]
Hello,

Here's some minor bug I encounted while I wasn't explicitely using the `six` package. The description is pretty long and uninteresting but it offers steps to reproduce the issue. A clearer (?) explanation is provided afterwards.

**Raw description and code sample**

I've add the following error:

```
E
======================================================================
ERROR: bug (unittest2.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
ImportError: Failed to import test module: bug
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 36, in <module>
    import _tkinter
ImportError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/some_path/my_new_env/lib/python3.5/site-packages/unittest2/loader.py", line 456, in _find_test_path
    module = self._get_module_from_name(name)
  File "/some_path/my_new_env/lib/python3.5/site-packages/unittest2/loader.py", line 395, in _get_module_from_name
    __import__(name)
  File "/home/josay/Geekage/six_bugs/bug.py", line 8, in <module>
    hasattr(o, 'toto')
  File "/some_path/my_new_env/lib/python3.5/site-packages/six.py", line 117, in __getattr__
    _module = self._resolve()
  File "/some_path/my_new_env/lib/python3.5/site-packages/six.py", line 114, in _resolve
    return _import_module(self.mod)
  File "/some_path/my_new_env/lib/python3.5/site-packages/six.py", line 81, in _import_module
    __import__(name)
  File "/usr/lib/python3.5/tkinter/__init__.py", line 38, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package
----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```

runnning the following command

`python -m unittest2 discover --start-directory=. --pattern=*.py`

in a Python 3.5 virtual env on the following code:

```
import gc
objs = gc.get_objects()
for o in objs:
    hasattr(o, 'toto')
```

(Using unittest2 is required to ensure that `six` gets somehow loaded automatically. Just running the code directly leads to no error.)

**Details**

The `MovedModule.__getattr__` method may raise an ImportError .

**Expectation**

From https://docs.python.org/2/reference/datamodel.html#object.__getattr__ : 

> Called when an attribute lookup has not found the attribute in the usual places (i.e. it is not an instance attribute nor is it found in the class tree for self). name is the attribute name. This method should return the (computed) attribute value or raise an AttributeError exception.

Thus, I'd expect an AttributeError to be raised when the import in __getattr__ fails. Then it would be caught by `hasattr` or `getattr` with a default value.

**Potential fix**

Rewriting the method likes this seems to fix the problem:

```
   def __getattr__(self, attr):
        try:
            _module = self._resolve()
        except ImportError:
            raise AttributeError("ImportError during __getattr__")
        value = getattr(_module, attr)
        setattr(self, attr, value)
        return value

```
I'm happy to submit a pull-request if you think it makes sense.

**Comment by SylvainDe** [comment]
Should I go for a pull-request directly ?

**Comment by benjaminp** [comment]
`MovedModule` is merely a clever hack design to be used with the `import` statement. In general, `__getattr__` methods can do arbitrary things and raise arbitrary exceptions, so I think you're going to have to handle that sort mischief in your generic object-walking code.
