### ISSUE TITLE
setuptools now depends on six, and vice versa

### ISSUE THREAD

**Issue by mjpieters** [benjaminp/six#183]
With cd3a8e98b8d1cbfc8117b95da55628eda534947b, `six` now unconditionally uses `setuptools`, yet setuptools [depends on `six`](https://github.com/pypa/setuptools/blob/master/setup.py#L165-L169).

Reverting the linked change would fix this trivially.

**Comment by mjpieters** [comment]
And the relevant `setuptools` discussion: https://github.com/pypa/setuptools/issues/980

**Comment by tgamblin** [comment]
See the discussion in pypa/setuptools#980.  Would it be possible for `six` to ensure that it always builds with only `distutils`?

**Comment by jakirkham** [comment]
At a bare minimum, we should be able to fallback to `distutils`, right?

**Comment by benjaminp** [comment]
I can't say I have a strong opinion about how to solve this. I hope some PyPA person can make an authoritative call.

**Comment by jaraco** [comment]
I don't have an authoritative answer, unfortunately. My instinct, however, is that by unconditionally using just distutils, builds with pip will use the shim that monkeypatches distutils, so pip-built wheels will be built with setuptools, so using a fallback is probably the best option. I hate to see the conditional distutils/setuptools dance, but it's only for the dependencies of setuptools, so probably worth the wart.

**Comment by mjpieters** [comment]
Just use distutils as a fallback; you want all the nice setuptools features for day-to-day development, and a working install when bootstrapping setuptools itself. Make sure to include a comment to avoid having to put it back in a 3rd time later. ;-)

**Comment by tgamblin** [comment]
I updated #184 to fall back instead of using `distutils` exclusively.
