### ISSUE TITLE
NameError: global name ‘AbstractType’ is not defined

### ISSUE THREAD

**Issue by sineo** [benjaminp/six#199]
Hi,

I'm currently getting an issue with Graphene and Six. I'm on OSX Yosemite and using six 1.10.0. with pyhton 2.7.
Here's the traceback:

/Library/Python/2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.login is deprecated, use flask_login instead.
  .format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
  File “run.py”, line 1, in <module>
    from application import application
  File “/Users/mmcartor/Sites/shiphero-api-v1/application.py”, line 29, in <module>
    import shiphero_app.core.database
  File “/Users/mmcartor/Sites/shiphero-api-v1/shiphero_app/core/database/__init__.py”, line 529, in <module>
    import graphene
  File “/Library/Python/2.7/site-packages/graphene/__init__.py”, line 19, in <module>
    from .types import (
  File “/Library/Python/2.7/site-packages/graphene/types/__init__.py”, line 3, in <module>
    from .objecttype import ObjectType
  File “/Library/Python/2.7/site-packages/graphene/types/objecttype.py”, line 6, in <module>
    from .abstracttype import AbstractTypeMeta
  File “/Library/Python/2.7/site-packages/graphene/types/abstracttype.py”, line 40, in <module>
    class AbstractType(six.with_metaclass(AbstractTypeMeta)):
  File “/Library/Python/2.7/site-packages/graphene/types/abstracttype.py”, line 24, in __new__
    if not issubclass(base, AbstractType) and issubclass(type(base), AbstractTypeMeta):
NameError: global name ‘AbstractType’ is not defined

Any help would be greatly appreciated.

**Comment by benjaminp** [comment]
This looks like an error with Graphene, namely that it has a metaclass that's attempting to refer to a class before it exists.
