### ISSUE TITLE
Feature Request: Error object compatibility

### ISSUE THREAD

**Issue by JesterEE** [benjaminp/six#202]
When working with Python 2.7 and 3.6, I found that the object that is returned from an error being caught has changed.

For example:
```
try:
   import nonexistent_module
except ImportError as e:
   print(dir(e))
```
The outputs are:
Python 2.7
```
['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__getitem__', '__getslice__', '__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__unicode__', 'args', 'message']
```
Python 3.6
```
['__cause__', '__class__', '__context__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__suppress_context__', '__traceback__', 'args', 'msg', 'name', 'path', 'with_traceback']
```

As can be seen, some stuff has changed.
Python 2.7
```
>>> e
>>> ImportError('No module named nonexistent_module')
>>> type(e)
>>> <type 'exceptions.ImportError'>
>>> e.args
>>> ('No module named nonexistent_module',)
>>> e.message
>>> 'No module named nonexistent_module' #  With a DeprecationWarning
```

Python 3.6
```
>>> e
>>> ModuleNotFoundError("No module named 'nonexistent_module'",)
>>> type(e)
>>> <class 'ModuleNotFoundError'>
>>> e.args
>>> ("No module named 'nonexistent_module'",)
>>> e.msg
>>> "No module named 'nonexistent_module'"
```
It would be nice if `six` could provide this object model compatibility.

**Comment by benjaminp** [comment]
`six` can't really change the error that `import` raises. To get the message out an exception, though, you can use `str(e)` on both Python 2 and 3.

**Comment by JesterEE** [comment]
@benjaminp I understand that.  Now that I think about it, since the raised error is interpreter  dependent, the only thing `six` "could" do is provide a wrapper for the returned exception to make them look the same after it is caught.

Something like
```
try:
   import nonexistent_module
except ImportError as e:
   e = six.ExceptionWrapperClass(e)
```
```
>>> e
>>> ExceptionWrapperClass("No module named 'nonexistent_module'",)
>>> type(e)
>>> <class 'six.ExceptionWrapperClass'>
>>> e.args
>>> ("No module named 'nonexistent_module'",)
>>> e.message  # Python2-like
>>> "No module named nonexistent_module"
>>> e.msg  # Python3-like
>>> "No module named 'nonexistent_module'"
```
I see 'some' value in this, for users that check the `message`/`msg` attributes, but as you pointed out `str(e)` is easier to write and the only difference between the output is a set of quotes that can easily be `str(e).replace("'", "")`d out.  I know that I probably wouldn't use `six` to do this unless I needed to catch a  lot of errors and I didn't want a lot of redundant string manipulations all over the place.

I'll close this out.
