### ISSUE TITLE
Add a mechanism like 'loadmodule(2, 3)' for loading other external libs

### ISSUE THREAD

**Issue by eode** [benjaminp/six#222]
Just a thought, and it may be out of the scope of six, but it might be nice to have a means of handling imports for other projects that aren't covered by six -- like:

```
something = six.load_module('some.py2module', 'py3module')
only2orNone = six.load_module('some.py2module', None)
only3orNone = six.load_module(None, 'py3module')
```
..the idea is to provide more succinct syntax when loading compat libs.  ..that's all.

**Comment by benjaminp** [comment]
Note, it is possible to [add your own renames to `six.moves`](https://six.readthedocs.io/#advanced-customizing-renames).
