### ISSUE TITLE
Make 2to3 use six

### ISSUE THREAD

**Issue by KOLANICH** [benjaminp/six#243]
In fact it is a bit late to suggest this: python 2 is near its EOL. Anyway, I guess there will be 3to4, and this idea is also valid for `twelve`.

**Comment by benjaminp** [comment]
Can you expand on what you are suggesting? `six` is a library and `2to3` is a command-line tool.

**Comment by KOLANICH** [comment]
@benjaminp , the code emited by 2to3 is suitable only for python 3. I use python 3 only, so if a library doesn't support python 3 I use `2to3`. It often requires manual fixes. After these fixes I usually create a PR to the original repo. Some repo maintainers insist on non-dropping python 2 support, so I have to manually fix after `2to3` using `six` to make the code compatible to both python 2 qnd python 3. I guess `2to3` should have the mode emitting the code compatible with both python 2 and python 3.

**Comment by benjaminp** [comment]
I see. I believe [futurize](http://python-future.org/futurize.html) does something like that, though not using `six`. At any rate, this is really a `2to3` feature request, which isn't developed on this tracker.
