### ISSUE TITLE
indexbytes needs to be fixed for py3

### ISSUE THREAD

**Issue by itsmedivya** [benjaminp/six#244]
six.indexbytes returns int in all cases for Py2 whereas returns byte for list of byte in Py3. This is because six is using getitem internally which will not work for list of byte strings. In Py2, we use ord(buf[i]) which will return an int. 

```python
six.indexbytes([b'u'],0)                                                                           
PY3;  b'u'
PY2;  117
```

**Comment by benjaminp** [comment]
`six.indexbytes` is for use on (byte)strings not lists. Its behavior on other sequences is undefined.

**Comment by itsmedivya** [comment]
Thanks..
