### ISSUE TITLE
six.moves is not a module?

### ISSUE THREAD

**Issue by TeknosQuet** [benjaminp/six#245]
Python Version: 3.5.0
OS: Windows XP (Don't ask why I still have it.)
IDE: PyDev for Eclipse
Modules: pyglet, pynput, six

When I put the six module in my project as package and I run my project, it says:

    from six.moves import queue
ImportError: No module named 'six.moves'

I don't know how to fix this.

**Comment by yassFar** [comment]
Did you install six ? 
Try `pip install six` first

**Comment by TeknosQuet** [comment]
Yes I just now got it installed and it works. But how would I make it work with my project without users who would use it manually install six?

**Comment by yassFar** [comment]
You could include the six module in your project, it's just a single file six.py

**Comment by TeknosQuet** [comment]
Ok well I already did that. I meant to ask if there was a way to use pip to install a module within the code?

**Comment by yassFar** [comment]
You can do this:

`try:`
`    import six`
`except ImportError:`
`    import pip`
`    pip.main(['install', 'six'])`
`    import six`

**Comment by TeknosQuet** [comment]
Yay it works now! Thanks so much :)
