### ISSUE TITLE
Add assertLogs method

### ISSUE THREAD

**Issue by areading314** [benjaminp/six#248]
Would be great to have an `assertLogs` method, as was added to `unittest` in python 3.4, which does not exist in 2.7. This is a pain to have to reimplement from scratch and will help backwards compatibility for projects that assert on logging behavior in tests

**Comment by benjaminp** [comment]
Can't you use [unittest2](https://pypi.io/pypi/unittest2)?

**Comment by areading314** [comment]
@benjaminp will look at this, thanks
