### ISSUE TITLE
error while importing pkg_resource

### ISSUE THREAD

**Issue by elizabethjohanass** [benjaminp/six#263]
import pkg_resources
my_data = pkg_resources.resource_string(__name__, "godfather.zip")
with open("d:\\gotmine.zip","wb") as output:
            output.write(my_data)
except Exception as e:
        print("Error Name " + str(e))
i was trying to read bytes from package in python working on windows platform  while i was working in vs2015 i debug and test code it worked fine.
but when i compiled this code on pyinstaller to make it runnable exe.
it generates an exe but after i run exe it gives error
"can not import name six"
after i added to check on which line it got this error its on first line while importing pkg_resource.
could some one tell me what is the issue and how to fix it?

**Comment by graingert** [comment]
@elizabethjohanass This is not a six issue, it's a pkg_resources issue.

try this instead
```python
from importlib import resources as importlib_resources
my_data = importlib_resources.read_text(__package__, 'godfather.zip')
```
