### ISSUE TITLE
Add support for BrokenPipeError

### ISSUE THREAD

**Issue by cjerdonek** [benjaminp/six#274]
I think it would be useful to add functionality to support handling a broken pipe error across Python 2 and 3, as `BrokenPipeError` was introduced in Python 3. I had to do this in a recent PR to pip (https://github.com/pypa/pip/pull/5907). It would have been useful in that case as it wasn't easy to figure out something that works (especially with Windows and non-Windows being different).

Here is the resulting code that was committed: https://github.com/pypa/pip/blob/e5f4bbb7ddff87f48f2b5815513e4211ccdde83a/src/pip/_internal/utils/logging.py#L40-L72

**Comment by benjaminp** [comment]
This seems like a special case of #201.

**Comment by cjerdonek** [comment]
Yes, it looks like a special case.

**Comment by cjerdonek** [comment]
Closing as duplicate of #201.
