### ISSUE TITLE
Rationale for `reraise` choice: `tb = None` instead of `del tb`?

### ISSUE THREAD

**Issue by mentalisttraceur** [benjaminp/six#278]
I don't see this documented anywhere, and I'm just trying to understand:

What's the reason for preferring `tb = None` instead of `del tb` in the implementation of `reraise`?

**Comment by benjaminp** [comment]
Either one would work; that's just what I wrote.

**Comment by mentalisttraceur** [comment]
@benjaminp: in the commit history it was originally done the `del` way, and then later changed to the `= None` way?

That's what made me wonder if maybe you had found a flaw in doing the `del` way and chose `= None` for some technical reason.

**Comment by benjaminp** [comment]
Good sleuthing! If there was an interesting underlying reason for d071f66238c5b820f61c030684263b13a687d60e, I would have put it in the commit message.

**Comment by mentalisttraceur** [comment]
@benjaminp Okay, makes sense. Thank you for the clarification!
