### ISSUE TITLE
Rationale for `reraise` choice: `value` unset in PY3 but not PY2?

### ISSUE THREAD

**Issue by mentalisttraceur** [benjaminp/six#279]
Along with my [other question](https://github.com/benjaminp/six/issues/278) I'm having trouble understanding why `value = None` is being done only in Python 3 and not in Python 2? Wouldn't it be safer against reference cycles to just wipe them all out, just in case?

Is it because in Python 3 we know that `value` **for sure will** hold a reference to `tb`, while in Python 2 `value` **probably does not** hold a reference to `tb`?

That's what I've been able to think of on my own, because in Python 2 the calling code would have to go out of its way to create a reference cycle with `value`, while in Python 3 the calling code could do everything right and still get a reference cycle, so `reraise` is just protecting against the cases that calling code cannot protect itself from?

I guess also my intuition is that it would be most resilient against reference cycles (even pathological ones where the calling code did something really wrong) to just `tp = value = tb = None` in all cases in the `finally` - not saying that this is what you should do, just trying to understand if I am wrong about that, or if there is any other rationale I'm missing?

**Comment by benjaminp** [comment]
Python 3 exceptions hold a reference to the traceback in their `__traceback__` attribute. See https://www.python.org/dev/peps/pep-3134/.

**Comment by mentalisttraceur** [comment]
I know about the reference cycle caused by `__traceback__` on exception instances.

I feel like either I didn't explain my question clearly, or you stopped idea-fitting possible meanings onto my question words too early.

My point is: is it possible for the caller of `reraise` to *manually* make more of the same kind of reference cycles the same way in *any* Python version?

For example, if the caller attaches the traceback object *manually* to the exception object before passing it in (for whatever reason, as whatever attribute name)?

More precisely - is there *anything* that a caller could attach to any of the objects passed in, which in combination with the traceback bubbling up referencing each stack frame referencing locals along the way, would create *another* reference cycle?

And if so, then could there be a way where they do "everything right" and setting all three of `tp`, `value`, and `tb` within `reraise` remains the one thing that needs to happen for there to not be a reference cycle in this case?

My intuition says yes to both, but I haven't thought through all the possibilities "far enough" to feel rigorously-proven certainty.

I was hoping that you had thought through these corner-cases further and more thoroughly than I had.

Thank you for your time, in any case.

**Comment by benjaminp** [comment]
Setting `value = None` is meant to eliminate the "standard" reference cycle; it's not intended to be an exhaustive defence. In general, you can cause any ingenuous Python function make reference cycles by passing it weird parameters. Think of the variable clearing as an optimization rather than a guarantee, particularly since it's not relevant for non-CPython implementations.
