### ISSUE TITLE
six.moves.UserDict should alias to UserDict.IterableUserDict on Python 2

### ISSUE THREAD

**Issue by mgedmin** [benjaminp/six#281]
Python 2.7's UserDict.UserDict is not iterable.  Python 3's collections.UserDict is iterable.  Python 2.7 has a UserDict.IterableUserDict that _is_ iterable, so I think it would be better if six.moves.UserDict pointed to it instead of the other one.

**Comment by zevdg** [comment]
For anyone else who runs across this like I did, this snippet does the trick without conditionally importing different UserDict classes.

```
from six.moves import UserDict

if six.PY2:
  UserDict.__iter__ = lambda self: iter(self.data)
```
