### ISSUE TITLE
Question: Should I still use six.StringIO in python 2.6/3.4 polyglot?

### ISSUE THREAD

**Issue by plouj** [benjaminp/six#283]
Or should I use the core `io.StringIO` which appears to be available in both: https://docs.python.org/release/2.6.9/library/io.html#io.StringIO https://docs.python.org/release/3.2/library/io.html?

**Comment by mcepl** [comment]
I would certainly go for the later (don't use six when not necessary).

**Comment by joaoe** [comment]
In python 2, io.StringIO() expected unicode objects. In python 3 it expeted str objects. So, if you have code using str, io.StringIO will crash.

**Comment by mcepl** [comment]
That's true, sorry.

**Comment by benjaminp** [comment]
I recommend using `io` if you can. Though, as noted, that can sometimes be difficult on Python 2 because of `io.StringIO`'s requirement for `unicode`.

**Comment by eli-schwartz** [comment]
I'd go one step further and say using six.StringIO is laying time bombs for yourself. Your code should know whether it is using a bytes type or a unicode type, and act appropriately, e.g. getting to a point where unicode_literals is a core concept. If that's the case, then all your non-BytesIO strings are already unicode.

In one project I helped port, nearly every use of StringIO.StringIO needed to be ported to io.BytesIO, so using six.StringIO would be... bad. :D
