### ISSUE TITLE
Add number_types

### ISSUE THREAD

**Issue by joaoe** [benjaminp/six#293]
There is already `integer_types` which purpose is to abstract away `long` which exists only in python2.

So, if I have code `isinstance(value, six.integer_types)`, that will work for integers. However, if I wanted to test for any number I would have to write `isinstance(value, six.integer_types + (float,))` for instance, which is ugly.

Request: add `number_types` that supports any real number
```
try:
    number_types = (int, long, float)

except NameError:
    number_types = (int, float)
```

so then one can write `isinstance(value, six.number_types)`.

**Comment by benjaminp** [comment]
You can write `isinstance(v, (six.integer_types, float))`.

**Comment by joaoe** [comment]
Oh... apparently isinstance flattens the tuples at any depth ! Ok, then should work. Thanks !
