### ISSUE TITLE
`six.moves.urllib.parse` is not RFC 8089 compliant

### ISSUE THREAD

**Issue by Qix-** [benjaminp/six#300]
Ref pypa/packaging#120 and pypa/pip#6658.

`six.moves.urllib.parse` is not properly parsing `file://` protocol URIs and as such is causing issues in downstream usage by Pip.

The above two issues hold all of the information and investigations into this issue; please let me know if any information is missing.

**Comment by benjaminp** [comment]
`six.moves.urllib.parse` is simply the stdlib's [`urllib.parse`](https://docs.python.org/3/library/urllib.parse.html). So, if there's an behavior bug in it, the report belongs in the [CPython issue tracker](https://bugs.python.org).

**Comment by Qix-** [comment]
Sure enough, sorry I didn't catch that before and apologies for the noise @benjaminp  :)

**Comment by piotr-dobrogost** [comment]
@Qix- 
Have you found out if this bug had been raised on CPython issue tracker?

**Comment by Qix-** [comment]
@piotr-dobrogost To my knowledge it has not.
