### ISSUE TITLE
Package not install everytime

### ISSUE THREAD

**Issue by a1-mukul** [benjaminp/six#302]
Six Package not installed
There is a issue whenever we use pip3 install six it only downloads a six-1.12.0.dist-info folder but it does not give the package.
I have tried it multiple times by pip too.
 
I have to download files maually and place it to that package.

**Comment by graingert** [comment]
Sounds like a pip bug. Try `pip install -U pip`.

If you can repeat the issue try to create a minimal reproducible example in a VM image or Dockerfile and raise the issue on https://github.com/pypa/pip

**Comment by benjaminp** [comment]
We would at least need to see the actual error to debug.
