### ISSUE TITLE
Test failure with Python 3.9 due to _dummy_thread removal

### ISSUE THREAD

**Issue by stratakis** [benjaminp/six#317]
When running the tests with Python 3.9 test_move_items fails with ModuleNotFound error. That module was removed with Python 3.9: https://bugs.python.org/issue37312

_dummy_thread should be replaced with _thread

**Comment by benjaminp** [comment]
Too bad Travis doesn't provide 3.9. I thought that would be what `nightly` is, but that seems to be the 3.8 branch.

**Comment by hroncok** [comment]
https://travis-ci.community/t/python-3-9-support/6703/4
https://github.com/travis-ci/travis-nightly-builder/commit/41c2123408374d96044986ef1347427e5c38f5ac

**Comment by hroncok** [comment]
Thank You!
