### ISSUE TITLE
six.moves htmlentitydefs error

### ISSUE THREAD

**Issue by alan1world** [benjaminp/six#328]
Error during import:

```
from htmlentitydefs import codepoint2name, name2codepoint
ModuleNotFoundError: No module named 'htmlentitydefs'
```
Code is not trying to use 'htmlentitydefs':

`from six.moves.html_entities import codepoint2name, name2codepoint`

In Python 3.8, `html.entities.entitydefs, html.entities.name2codepoint, html.entities.codepoint2name` are all under `html.entities`  not `htmlentitydefs`

**Comment by gungnix** [comment]
I don't understand your problem. Six lets you import codepoint2name etc. in Python2 and Python3 with the six.moves statement you posted. Works as designed.

**Comment by alan1world** [comment]
Yes, sorry, pip has an old version of the code which does not use six and hence the error.
I've emailed the maintainer to update pip to the current version.
