### ISSUE TITLE
Implement create_module() and exec_module() for _SixMetaPathImporter

### ISSUE THREAD

**Issue by brettcannon** [benjaminp/six#341]
Use of `load_module()` when `exec_module()` is not defined will raise an `ImportWarning` in Python 3.10.

**Comment by frenzymadness** [comment]
For context: https://bugs.python.org/issue26131 & https://github.com/python/cpython/pull/23469

**Comment by webknjaz** [comment]
Extra context: https://github.com/pypa/setuptools/issues/2481.

**Comment by webknjaz** [comment]
Reproducer:
```python-traceback
$ python3.10 -W error -c 'import six.moves.urllib_parse'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1026, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1005, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 681, in _load_unlocked
ImportWarning: _SixMetaPathImporter.exec_module() not found; falling back to load_module()
```

**Comment by webknjaz** [comment]
### pytest workaround :point_down: 

Here's an example of how to suppress the warning until fixed: https://github.com/cherrypy/cheroot/commit/5fbcb251f56521bfc70eb603f65e0720168b7be3

**Comment by frenzymadness** [comment]
Honestly, this is causing us a lot of problems because we are already testing all Python packages in Fedora with the latest Python 3.10. It would be great if somebody who understands the magic of these methods proposes a fix. The warning can be suppressed by we are not able to do it in hundreds of packages and we'd very like to fix the core problem.

If nobody with a better understanding do it, I'll take a look next week.

**Comment by webknjaz** [comment]
I've tried the look into this yesterday but there's no clear examples of implementing the required methods (there's +1 extra method necessary).

@frenzymadness if you have a centralized place in the infra, you could try to use a `PYTHONWARNINGS` env var for that.

**Comment by vstinner** [comment]
To reproduce the issue:

```
$ python3.10 -Werror -c 'from six.moves import _thread'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1026, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1005, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 681, in _load_unlocked
ImportWarning: _SixMetaPathImporter.exec_module() not found; falling back to load_module()
```

**Comment by vstinner** [comment]
I wrote PR #343 to fix this issue.
