### ISSUE TITLE
ModuleNotFoundError: No module named 'six.moves' 

### ISSUE THREAD

**Issue by GGXBoo** [benjaminp/six#387]
My system environment: Ubuntu 24.04
six version:1.16.0
python: 3.12.3
When I execute the python program, the following error occurs：
![image](https://github.com/user-attachments/assets/d2d5a137-1a60-4afa-897a-a2f5bd3ffd9f)

I'm not sure what happened. I saw other people encountered the same error in the issue and tried some solutions but they didn't work.

If you have time, please help me look into this issue.

Thanks!

**Comment by saurik** [comment]
@GGXBoo Are you sure this is not using a bundled older version of six? I am running into a very similar-looking issue, and the program I am running (ycqlsh from yugabytedb) has a copy of six 1.12.0 as a .zip which it inserts into the start of sys.path. If I just run my own interpreter, then importing from six.moves works fine.

**Comment by GGXBoo** [comment]
> @GGXBoo Are you sure this is not using a bundled older version of six? I am running into a very similar-looking issue, and the program I am running (ycqlsh from yugabytedb) has a copy of six 1.12.0 as a .zip which it inserts into the start of sys.path. If I just run my own interpreter, then importing from six.moves works fine.

Yes, This  is indeed using a bundled older version of six，I tried using a higher version and it worked.
Thanks for your reply

**Comment by Ariya12138** [comment]
great！
