### ISSUE TITLE
http://pythonhosted.org/six/ docs are not up to date

### ISSUE THREAD

**Issue by benjaminp** [benjaminp/six#58]
Originally reported by: **Marc Abramowitz (Bitbucket: [msabramo](https://bitbucket.org/msabramo), GitHub: [msabramo](https://github.com/msabramo))**

----------------------------------------

I think http://pythonhosted.org/six/ needs to be rebuilt.

It says that Python 2 and Python 3 both have `xmlrpclib` which is not correct and was already fixed in e7179a1b4a63.

----------------------------------------
- Bitbucket: https://bitbucket.org/gutworth/six/issue/58

**Comment by graingert** [comment]
@benjaminp they're outdated again - and pythonhosted appears higher in google. Can you remove it and redirect to rtfd?

**Comment by benjaminp** [comment]
I deleted the PyPI ones.
