### ISSUE TITLE
pipes.quote moved to shlex.quote

### ISSUE THREAD

**Issue by benjaminp** [benjaminp/six#90]
Originally reported by: **Florian Wilhelm (Bitbucket: [florianwilhelm](https://bitbucket.org/florianwilhelm), GitHub: [florianwilhelm](https://github.com/florianwilhelm))**

----------------------------------------

The Python 2 pipes.quote function has moved to shlex.quote in Python 3.
I think a six.moves.quote function should be provided to help deal with this transition.

----------------------------------------
- Bitbucket: https://bitbucket.org/gutworth/six/issue/90

**Comment by cben** [comment]
Eventually, the whole `pipes` module [went away in 3.13](https://docs.python.org/3.13/library/pipes.html) per [PEP 594](https://peps.python.org/pep-0594/) deprecation schedule.  
Good thing you had the foresight a decade ago to provide `six.moves.shlex_quote` transition path anyway 😎
